### ISSUE TITLE
Error: Unsupported protocol "null in URL: ""

### ISSUE THREAD

**Issue by Zxce3** [trello-talk/WebhookAPI#261]
So I run this project with PostgreSQL database and it doesn't populate the influx db

the error output:
```bash
Error: Unsupported protocol "null in URL: ""
    at new at (/home/user/projek/WebhookAPI/node_modules/@influxdata/influxdb-client/dist/index.js:16:1229)
    at new exports.InfluxDB (/home/user/projek/WebhookAPI/node_modules/@influxdata/influxdb-client/dist/index.js:16:7789)
    at Object.<anonymous> (/home/user/projek/WebhookAPI/dist/db/influx.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user/projek/WebhookAPI/dist/util/webhookData.js:12:18)
●  Process exit with code 1, signal: null

```

**Comment by Snazzah** [comment]
Ah yeah, at the moment it doesn't support *not* using InfluxDB. Will fix in a later release.
